# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\0Good\SCHOLL\compu\y13 oproject\random image first try.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2038, 1059)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pictures = QtWidgets.QLabel(self.centralwidget)
        self.pictures.setGeometry(QtCore.QRect(10, 10, 1728, 972))
        self.pictures.setText("")
        self.pictures.setPixmap(QtGui.QPixmap("D:\\0Good\\SCHOLL\\compu\\y13 oproject\\part 1/Subaru Impreza WRX STI 1st gen.png"))
        self.pictures.setScaledContents(True)
        self.pictures.setObjectName("pictures")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 900, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(162, 219, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.continue_button = QtWidgets.QPushButton(self.centralwidget)
        self.continue_button.setGeometry(QtCore.QRect(900, 900, 321, 71))
        self.continue_button.setObjectName("continue_button")
        self.reroll_button = QtWidgets.QPushButton(self.centralwidget)
        self.reroll_button.setGeometry(QtCore.QRect(560, 900, 331, 71))
        self.reroll_button.setObjectName("reroll_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(20, 900, 131, 71))
        self.back_button.setObjectName("back_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2038, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Here is random your image"))
        self.continue_button.setText(_translate("MainWindow", "Continue"))
        self.reroll_button.setText(_translate("MainWindow", "Next"))
        self.back_button.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
